language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - jruby
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: oraclejdk8
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: oraclejdk8
    - rvm: 2.1.1
      jdk: openjdk6
    - rvm: 2.1.1
      jdk: oraclejdk7
    - rvm: 2.1.1
      jdk: oraclejdk8
    - rvm: 2.1.2
      jdk: openjdk6
    - rvm: 2.1.2
      jdk: oraclejdk7
    - rvm: 2.1.2
      jdk: oraclejdk8
    - rvm: 2.1.3
      jdk: openjdk6
    - rvm: 2.1.3
      jdk: oraclejdk7
    - rvm: 2.1.3
      jdk: oraclejdk8
    - rvm: 2.1.4
      jdk: openjdk6
    - rvm: 2.1.4
      jdk: oraclejdk7
    - rvm: 2.1.4
      jdk: oraclejdk8
addons:
  code_climate:
    repo_token: 87dd0b9f07405e5835164de6f246b33f1baf908e72b4c493db23cd71da7da60f